function wt_about_wt
% WT_ABOUT_WT Show 'About WT' dialog

cAboutText = { ...
        'Whisker Tracker (WT)', ...
        ['Build version ' wt_get_build_number], ...
        ' ', ...
        'Contributors:', ...
        '    Per Magne Knutsen', ...
        '    Dori Derdikman', ...
        '    Aharon Sheer', ...
        '    Naama Rubin', ...
        ' ', ...
        'Online Documentation: http://code.google.com/p/whiskertracker/', ...
        'Discussion Group: http://groups.google.com/group/WhiskerTracker', ...
        ' ', ...
        'Please cite any use of this software:', ...
        'Knutsen, Derdikman, Ahissar (2005), Tracking whisker and head movements of unrestrained, behaving rodents, J. Neurophys, 2005', ...
    };

msgbox(cAboutText, 'About WT')
