function convert_open_virtual_pole_file(sWT)
% Script for automating conversion of video files acquired by the Virtual
% Pole application by Idan Steinberg. The script will prompt for a file to
% be selected. The file must reside in the same directory as the text file
% associated with the video generated by Virtual Pole.
%
% The Virtual Pole generated video file will be converted to AVI by Matlab
% and saved to disk. The original file is not modified in any way. This
% script will then proceed to open the AVI file in WT.
%
% Authored by Per Magne Knutsen <pknutsen@ucsd.edu>, April 2009
%

BaslerConvertTool

return
